package com.lms.backend.audit;

public enum AuditAction {
    TEACHER_REGISTERED,
    STUDENT_REGISTERED,
    COURSE_SUBMITTED,
    TEACHER_APPROVED,
    TEACHER_REJECTED,
    TEACHER_SUSPENDED,
    TEACHER_ACTIVATED,
    STUDENT_APPROVED,
    STUDENT_REJECTED,
    STUDENT_SUSPENDED,
    STUDENT_ACTIVATED,
    COURSE_APPROVED,
    COURSE_REJECTED,
    COURSE_SUSPENDED,
    ENROLLMENT,
    ASSIGNMENT_SUBMITTED,
    ASSIGNMENT_GRADED,
    QUIZ_COMPLETED
}